AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda application that calls the Lambda API.
Parameters:
  EnvironmentName:
    Type: String
    Default: dev
Resources:
  GetExampleDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://capstone-dreamteamrepo-artifacts/dbe25f0f1dbc1989818e8386d59d3c88
      Handler: com.kenzie.capstone.service.lambda.GetExampleData
      Runtime: java11
      Description: Get Example Data for given id
      MemorySize: 512
      Timeout: 240
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      - AmazonS3FullAccess
      - AmazonDynamoDBFullAccess
      Tracing: Active
      Events:
        UpdateResource:
          Type: Api
          Properties:
            Path: /example/{id}
            Method: get
  SetExampleDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://capstone-dreamteamrepo-artifacts/dbe25f0f1dbc1989818e8386d59d3c88
      Handler: com.kenzie.capstone.service.lambda.SetExampleData
      Runtime: java11
      Description: Set Example Data
      MemorySize: 512
      Timeout: 240
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      - AmazonS3FullAccess
      - AmazonDynamoDBFullAccess
      Tracing: Active
      Events:
        UpdateResource:
          Type: Api
          Properties:
            Path: /example
            Method: post
  GetRecipeDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://capstone-dreamteamrepo-artifacts/dbe25f0f1dbc1989818e8386d59d3c88
      Handler: com.kenzie.capstone.service.lambda.GetRecipeData
      Runtime: java11
      Description: Get Recipe Data for dietary Restriction
      MemorySize: 512
      Timeout: 240
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      - AmazonS3FullAccess
      - AmazonDynamoDBFullAccess
      Tracing: Active
      Events:
        UpdateResource:
          Type: Api
          Properties:
            Path: /recipe/{dietaryRestriction}
            Method: get
  SetRecipeDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://capstone-dreamteamrepo-artifacts/dbe25f0f1dbc1989818e8386d59d3c88
      Handler: com.kenzie.capstone.service.lambda.SetRecipeData
      Runtime: java11
      Description: Set Recipe Data
      MemorySize: 512
      Timeout: 240
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      - AmazonS3FullAccess
      - AmazonDynamoDBFullAccess
      Tracing: Active
      Events:
        UpdateResource:
          Type: Api
          Properties:
            Path: /recipe
            Method: post
